[package]
name = "random"
version = "0.1.0"
edition = "2018"

[dependencies]
rand="0.7.0"
rand_core="0.5.0"
rand_os="0.2.0"
rand_jitter="0.2.0"
rand_chacha="0.2.0"
rand_hc="0.2.0"
rand_isaac="0.2.0"
rand_xorshift="0.2.0"
rand_pcg="0.2.0"
rand_xoshiro="0.3.0"
chrono="0.4.7"